<?xml version="1.0" encoding="utf-8"?><Database Name="MF_DB" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\MF_DB.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MF_DBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Supliers_Table" Member="Supliers_Tables">
    <Type Name="Supliers_Table">
      <Column Name="SuplierId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SuplierUsername" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CellNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ShopAddress" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SuplierName" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="Supliers_Table_Product" Member="Products" ThisKey="SuplierId" OtherKey="SuplierId" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Prod_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Prod_Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Prod_Type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Snap_Path" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SuplierId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Supliers_Table_Product" Member="Supliers_Table" ThisKey="SuplierId" OtherKey="SuplierId" Type="Supliers_Table" IsForeignKey="true" />
    </Type>
  </Table>
</Database>